import type { LocaleSeed, SlugSeed } from '@sveltebuilder/hermes-schema/seed';

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

export function generateBaseSeedSql(locales: readonly LocaleSeed[], slugs: readonly SlugSeed[]): string {
  const sections: string[] = [
    '-- ============================================================',
    '-- Generated by sveltebuilder sync:supabase — do not edit',
    '-- ============================================================',
    '',
  ];

  // Locales
  const localeRows = locales
    .map((l) => `  ('${esc(l.code)}', '${esc(l.name)}', '${esc(l.nativeName)}', '${l.dir}')`)
    .join(',\n');
  sections.push(
    '-- Locales',
    `insert into public.locale (code, name, native_name, dir) values\n${localeRows}\non conflict (code) do nothing;`,
    '',
  );

  // local_text_link entries (all global scope, no entity_id)
  const linkRows = slugs
    .map((s) => `  ('${esc(s.slug)}', null, null)`)
    .join(',\n');
  sections.push(
    '-- local_text_link entries',
    `insert into public.local_text_link (slug, scope, entity_id) values\n${linkRows}\non conflict do nothing;`,
    '',
  );

  // Translations — one insert block per locale code present in any slug
  const localeCodes = [...new Set(slugs.flatMap((s) => Object.keys(s.translations)))].sort();

  for (const code of localeCodes) {
    const rows = slugs
      .filter((s) => s.translations[code] !== undefined)
      .map((s) => `  ('${esc(s.slug)}', '${esc(s.translations[code]!)}')`);

    if (rows.length === 0) continue;

    sections.push(
      `-- Translations — ${code}`,
      `insert into public.local_text (link, locale, content)`,
      `select l.id, (select id from public.locale where code = '${esc(code)}'), v.content`,
      `from (values`,
      rows.join(',\n'),
      `) as v(slug, content)`,
      `join public.local_text_link l on l.slug = v.slug and l.scope is null and l.entity_id is null`,
      `on conflict (link, locale) do nothing;`,
      '',
    );
  }

  return sections.join('\n');
}
