-- Content module supplements: updated_at triggers, cross-package FKs.
--
-- RLS predicates use public.current_user_id() (bigint) and user_account.admin.
-- Never use auth.uid(), auth.jwt(), or uuid comparisons here.
--
-- Drizzle-kit generates CREATE TABLE for all content tables. This file adds:
--   1. set_updated_at() trigger function (not generated by Drizzle)
--   2. Triggers on article and comment for auto-updating updated_at
--   3. Cross-package FKs to user_account (cannot be expressed in the module schema)

-- ── updated_at trigger function ───────────────────────────────────────────────

create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

create trigger article_set_updated_at
  before update on public.article
  for each row execute function set_updated_at();

create trigger comment_set_updated_at
  before update on public.comment
  for each row execute function set_updated_at();

-- ── Cross-package foreign keys ────────────────────────────────────────────────

alter table public.article_assignment
  add constraint fk_article_assignment_user_account
  foreign key (user_account_id) references public.user_account(id) on delete cascade;

alter table public.article_revision
  add constraint fk_article_revision_user_account
  foreign key (user_account_id) references public.user_account(id) on delete cascade;

alter table public.author_profile
  add constraint fk_author_profile_user_account
  foreign key (user_account_id) references public.user_account(id) on delete set null;

alter table public.comment
  add constraint fk_comment_user_account
  foreign key (user_account_id) references public.user_account(id) on delete set null;

alter table public.media_asset
  add constraint fk_media_asset_uploaded_by
  foreign key (uploaded_by) references public.user_account(id) on delete restrict;
