-- ============================================================
-- Locales
-- ============================================================
insert into public.locale (code, name, native_name, dir) values
  ('en',    'English',             'English',            'ltr'),
  ('fr',    'French',              'Français',           'ltr'),
  ('es',    'Spanish',             'Español',            'ltr'),
  ('de',    'German',              'Deutsch',            'ltr'),
  ('pt-BR', 'Portuguese (Brazil)', 'Português (Brasil)', 'ltr'),
  ('ja',    'Japanese',            '日本語',               'ltr'),
  ('zh-CN', 'Chinese (Simplified)','简体中文',             'ltr'),
  ('ar',    'Arabic',              'العربية',            'rtl')
on conflict (code) do nothing;

-- ============================================================
-- Application dictionary — local_text_link entries
-- (scope = null for all global application copy)
-- ============================================================
insert into public.local_text_link (slug, scope, entity_id) values
  ('app.name',               null, null),
  ('app.tagline',            null, null),
  ('nav.home',               null, null),
  ('nav.back',               null, null),
  ('nav.menu',               null, null),
  ('nav.close',              null, null),
  ('nav.search',             null, null),
  ('action.save',            null, null),
  ('action.cancel',          null, null),
  ('action.confirm',         null, null),
  ('action.delete',          null, null),
  ('action.edit',            null, null),
  ('action.submit',          null, null),
  ('action.continue',        null, null),
  ('action.back',            null, null),
  ('action.close',           null, null),
  ('action.add',             null, null),
  ('action.remove',          null, null),
  ('action.view',            null, null),
  ('action.loading',         null, null),
  ('feedback.success',       null, null),
  ('feedback.error',         null, null),
  ('feedback.not_found',     null, null),
  ('feedback.unauthorized',  null, null),
  ('feedback.empty',         null, null),
  ('feedback.required',      null, null),
  ('feedback.saving',        null, null),
  ('feedback.saved',         null, null),
  ('feedback.confirm_delete',null, null),
  ('locale.select',          null, null),
  ('locale.current',         null, null),
  ('pagination.next',        null, null),
  ('pagination.previous',    null, null),
  ('pagination.page',        null, null),
  ('pagination.of',          null, null),
  ('user.profile',           null, null),
  ('user.settings',          null, null),
  ('user.sign_in',           null, null),
  ('user.sign_out',          null, null),
  ('user.sign_up',           null, null),
  ('user.email',             null, null),
  ('user.password',          null, null),
  ('user.forgot_password',   null, null),
  ('user.sign_in.subtitle',                null, null),
  ('admin.title',                          null, null),
  ('admin.nav.dashboard',                  null, null),
  ('admin.dashboard.title',                null, null),
  ('admin.dashboard.recent.title',         null, null),
  ('admin.stats.key_metrics',              null, null),
  ('admin.dashboard.stat.total_users',     null, null),
  ('admin.dashboard.stat.active_sessions', null, null),
  ('admin.dashboard.stat.published',       null, null),
  ('admin.dashboard.stat.pending_review',  null, null),
  ('table.id',                             null, null),
  ('table.name',                           null, null),
  ('table.status',                         null, null),
  ('table.date',                           null, null),
  ('table.actions',                        null, null),
  ('action.view_all',                      null, null),
  ('admin.nav.label',                      null, null),
  ('nav.pagination',                       null, null),
  ('post.categories',                      null, null),
  ('post.tags',                            null, null),
  ('post.comments',                        null, null),
  -- local-text admin
  ('admin.nav.local_text',                 null, null),
  ('admin.local_text.title',               null, null),
  ('admin.local_text.slug',                null, null),
  ('admin.local_text.scope',               null, null),
  ('admin.local_text.new',                 null, null),
  ('admin.local_text.edit',                null, null),
  ('admin.local_text.content',             null, null),
  -- locale admin
  ('admin.nav.locale',                     null, null),
  ('admin.locale.title',                   null, null),
  ('admin.locale.code',                    null, null),
  ('admin.locale.name',                    null, null),
  ('admin.locale.native_name',             null, null),
  ('admin.locale.dir',                     null, null),
  ('admin.locale.dir.ltr',                 null, null),
  ('admin.locale.dir.rtl',                 null, null),
  ('admin.locale.new',                     null, null),
  ('admin.locale.edit',                    null, null),
  -- navigation-item admin
  ('admin.nav.navigation_item',            null, null),
  ('admin.navigation_item.title',          null, null),
  ('admin.navigation_item.href',           null, null),
  ('admin.navigation_item.scope',          null, null),
  ('admin.navigation_item.sort_order',     null, null),
  ('admin.navigation_item.new',            null, null),
  ('admin.navigation_item.edit',           null, null),
  ('admin.navigation_item.active',         null, null)
on conflict do nothing;

-- ============================================================
-- English copy
-- ============================================================
insert into public.local_text (link, locale, content)
select
  l.id,
  (select id from public.locale where code = 'en'),
  l.content
from (values
  ('app.name',                'SvelteBuilder App'),
  ('app.tagline',             'Built with SvelteBuilder'),
  ('nav.home',                'Home'),
  ('nav.back',                'Back'),
  ('nav.menu',                'Menu'),
  ('nav.close',               'Close'),
  ('nav.search',              'Search'),
  ('action.save',             'Save'),
  ('action.cancel',           'Cancel'),
  ('action.confirm',          'Confirm'),
  ('action.delete',           'Delete'),
  ('action.edit',             'Edit'),
  ('action.submit',           'Submit'),
  ('action.continue',         'Continue'),
  ('action.back',             'Back'),
  ('action.close',            'Close'),
  ('action.add',              'Add'),
  ('action.remove',           'Remove'),
  ('action.view',             'View'),
  ('action.loading',          'Loading…'),
  ('feedback.success',        'Success'),
  ('feedback.error',          'Something went wrong'),
  ('feedback.not_found',      'Page not found'),
  ('feedback.unauthorized',   'You are not authorized to view this page'),
  ('feedback.empty',          'Nothing here yet'),
  ('feedback.required',       'This field is required'),
  ('feedback.saving',         'Saving…'),
  ('feedback.saved',          'Saved'),
  ('feedback.confirm_delete', 'Are you sure you want to delete this?'),
  ('locale.select',           'Select language'),
  ('locale.current',          'Current language'),
  ('pagination.next',         'Next'),
  ('pagination.previous',     'Previous'),
  ('pagination.page',         'Page'),
  ('pagination.of',           'of'),
  ('user.profile',            'Profile'),
  ('user.settings',           'Settings'),
  ('user.sign_in',            'Sign in'),
  ('user.sign_out',           'Sign out'),
  ('user.sign_up',            'Sign up'),
  ('user.email',              'Email'),
  ('user.password',           'Password'),
  ('user.forgot_password',    'Forgot password?'),
  ('user.sign_in.subtitle',                'Enter your credentials to access the admin area.'),
  ('admin.title',                          'Admin'),
  ('admin.nav.dashboard',                  'Dashboard'),
  ('admin.dashboard.title',                'Dashboard'),
  ('admin.dashboard.recent.title',         'Recent records'),
  ('admin.stats.key_metrics',              'Key metrics'),
  ('admin.dashboard.stat.total_users',     'Total users'),
  ('admin.dashboard.stat.active_sessions', 'Active sessions'),
  ('admin.dashboard.stat.published',       'Published'),
  ('admin.dashboard.stat.pending_review',  'Pending review'),
  ('table.id',                             'ID'),
  ('table.name',                           'Name'),
  ('table.status',                         'Status'),
  ('table.date',                           'Date'),
  ('table.actions',                        'Actions'),
  ('action.view_all',                      'View all'),
  ('admin.nav.label',                      'Admin navigation'),
  ('nav.pagination',                       'Pagination'),
  ('post.categories',                      'Categories'),
  ('post.tags',                            'Tags'),
  ('post.comments',                        'Comments'),
  ('admin.nav.local_text',                 'Content'),
  ('admin.local_text.title',               'Content administration'),
  ('admin.local_text.slug',                'Slug'),
  ('admin.local_text.scope',               'Scope'),
  ('admin.local_text.new',                 'New entry'),
  ('admin.local_text.edit',                'Edit entry'),
  ('admin.local_text.content',             'Content'),
  ('admin.nav.locale',                     'Locales'),
  ('admin.locale.title',                   'Locale administration'),
  ('admin.locale.code',                    'Code'),
  ('admin.locale.name',                    'Name'),
  ('admin.locale.native_name',             'Native name'),
  ('admin.locale.dir',                     'Text direction'),
  ('admin.locale.dir.ltr',                 'Left to right'),
  ('admin.locale.dir.rtl',                 'Right to left'),
  ('admin.locale.new',                     'New locale'),
  ('admin.locale.edit',                    'Edit locale'),
  ('admin.nav.navigation_item',            'Navigation'),
  ('admin.navigation_item.title',          'Navigation administration'),
  ('admin.navigation_item.href',           'URL'),
  ('admin.navigation_item.scope',          'Scope'),
  ('admin.navigation_item.sort_order',     'Sort order'),
  ('admin.navigation_item.new',            'New item'),
  ('admin.navigation_item.edit',           'Edit item'),
  ('admin.navigation_item.active',         'Active')
) as v(slug, content)
join public.local_text_link l on l.slug = v.slug and l.scope is null and l.entity_id is null
on conflict (link, locale) do nothing;

-- ============================================================
-- French copy
-- ============================================================
insert into public.local_text (link, locale, content)
select
  l.id,
  (select id from public.locale where code = 'fr'),
  l.content
from (values
  ('app.name',                'Application SvelteBuilder'),
  ('app.tagline',             'Construit avec SvelteBuilder'),
  ('nav.home',                'Accueil'),
  ('nav.back',                'Retour'),
  ('nav.menu',                'Menu'),
  ('nav.close',               'Fermer'),
  ('nav.search',              'Rechercher'),
  ('action.save',             'Enregistrer'),
  ('action.cancel',           'Annuler'),
  ('action.confirm',          'Confirmer'),
  ('action.delete',           'Supprimer'),
  ('action.edit',             'Modifier'),
  ('action.submit',           'Soumettre'),
  ('action.continue',         'Continuer'),
  ('action.back',             'Retour'),
  ('action.close',            'Fermer'),
  ('action.add',              'Ajouter'),
  ('action.remove',           'Supprimer'),
  ('action.view',             'Voir'),
  ('action.loading',          'Chargement…'),
  ('feedback.success',        'Succès'),
  ('feedback.error',          'Une erreur est survenue'),
  ('feedback.not_found',      'Page introuvable'),
  ('feedback.unauthorized',   'Vous n''êtes pas autorisé à voir cette page'),
  ('feedback.empty',          'Rien ici pour l''instant'),
  ('feedback.required',       'Ce champ est obligatoire'),
  ('feedback.saving',         'Enregistrement…'),
  ('feedback.saved',          'Enregistré'),
  ('feedback.confirm_delete', 'Êtes-vous sûr de vouloir supprimer ceci ?'),
  ('locale.select',           'Choisir la langue'),
  ('locale.current',          'Langue actuelle'),
  ('pagination.next',         'Suivant'),
  ('pagination.previous',     'Précédent'),
  ('pagination.page',         'Page'),
  ('pagination.of',           'sur'),
  ('user.profile',            'Profil'),
  ('user.settings',           'Paramètres'),
  ('user.sign_in',            'Se connecter'),
  ('user.sign_out',           'Se déconnecter'),
  ('user.sign_up',            'S''inscrire'),
  ('user.email',              'Courriel'),
  ('user.password',           'Mot de passe'),
  ('user.forgot_password',    'Mot de passe oublié ?'),
  ('user.sign_in.subtitle',                'Entrez vos identifiants pour accéder à la zone admin.'),
  ('admin.title',                          'Admin'),
  ('admin.nav.dashboard',                  'Tableau de bord'),
  ('admin.dashboard.title',                'Tableau de bord'),
  ('admin.dashboard.recent.title',         'Derniers enregistrements'),
  ('admin.stats.key_metrics',              'Indicateurs clés'),
  ('admin.dashboard.stat.total_users',     'Utilisateurs totaux'),
  ('admin.dashboard.stat.active_sessions', 'Sessions actives'),
  ('admin.dashboard.stat.published',       'Publié'),
  ('admin.dashboard.stat.pending_review',  'En attente de révision'),
  ('table.id',                             'ID'),
  ('table.name',                           'Nom'),
  ('table.status',                         'Statut'),
  ('table.date',                           'Date'),
  ('table.actions',                        'Actions'),
  ('action.view_all',                      'Tout voir'),
  ('admin.nav.label',                      'Navigation admin'),
  ('nav.pagination',                       'Pagination'),
  ('post.categories',                      'Catégories'),
  ('post.tags',                            'Étiquettes'),
  ('post.comments',                        'Commentaires'),
  ('admin.nav.local_text',                 'Contenus'),
  ('admin.local_text.title',               'Administration des contenus'),
  ('admin.local_text.slug',                'Identifiant'),
  ('admin.local_text.scope',               'Portée'),
  ('admin.local_text.new',                 'Nouvelle entrée'),
  ('admin.local_text.edit',                'Modifier l''entrée'),
  ('admin.local_text.content',             'Contenu'),
  ('admin.nav.locale',                     'Locales'),
  ('admin.locale.title',                   'Administration des locales'),
  ('admin.locale.code',                    'Code'),
  ('admin.locale.name',                    'Nom'),
  ('admin.locale.native_name',             'Nom natif'),
  ('admin.locale.dir',                     'Direction du texte'),
  ('admin.locale.dir.ltr',                 'De gauche à droite'),
  ('admin.locale.dir.rtl',                 'De droite à gauche'),
  ('admin.locale.new',                     'Nouvelle locale'),
  ('admin.locale.edit',                    'Modifier la locale'),
  ('admin.nav.navigation_item',            'Navigation'),
  ('admin.navigation_item.title',          'Administration de la navigation'),
  ('admin.navigation_item.href',           'URL'),
  ('admin.navigation_item.scope',          'Portée'),
  ('admin.navigation_item.sort_order',     'Ordre de tri'),
  ('admin.navigation_item.new',            'Nouvel élément'),
  ('admin.navigation_item.edit',           'Modifier l''élément'),
  ('admin.navigation_item.active',         'Actif')
) as v(slug, content)
join public.local_text_link l on l.slug = v.slug and l.scope is null and l.entity_id is null
on conflict (link, locale) do nothing;

-- ============================================================
-- Navigation
-- ============================================================
insert into public.navigation_item (local_text_link_id, href, scope, sort_order)
select l.id, nav.href, nav.scope, nav.sort_order
from (values
  ('admin.nav.dashboard',      '/admin/dashboard',      'admin', 10),
  ('admin.nav.local_text',     '/admin/local-text',     'admin', 20),
  ('admin.nav.locale',         '/admin/locale',         'admin', 30),
  ('admin.nav.navigation_item','/admin/navigation-item','admin', 40)
) as nav(slug, href, scope, sort_order)
join public.local_text_link l
  on l.slug = nav.slug and l.scope is null and l.entity_id is null
on conflict (href, scope) do nothing;
