export type SlugSeed = {
  slug: string;
  translations: Record<string, string>;
};

export const BASE_SLUGS: readonly SlugSeed[] = [
  { slug: 'app.name',                translations: { en: 'SvelteBuilder App',                                   fr: 'Application SvelteBuilder' } },
  { slug: 'app.tagline',             translations: { en: 'Built with SvelteBuilder',                            fr: 'Construit avec SvelteBuilder' } },
  { slug: 'nav.home',                translations: { en: 'Home',                                                fr: 'Accueil' } },
  { slug: 'nav.back',                translations: { en: 'Back',                                                fr: 'Retour' } },
  { slug: 'nav.menu',                translations: { en: 'Menu',                                                fr: 'Menu' } },
  { slug: 'nav.close',               translations: { en: 'Close',                                               fr: 'Fermer' } },
  { slug: 'nav.search',              translations: { en: 'Search',                                              fr: 'Rechercher' } },
  { slug: 'action.save',             translations: { en: 'Save',                                                fr: 'Enregistrer' } },
  { slug: 'action.cancel',           translations: { en: 'Cancel',                                              fr: 'Annuler' } },
  { slug: 'action.confirm',          translations: { en: 'Confirm',                                             fr: 'Confirmer' } },
  { slug: 'action.delete',           translations: { en: 'Delete',                                              fr: 'Supprimer' } },
  { slug: 'action.edit',             translations: { en: 'Edit',                                                fr: 'Modifier' } },
  { slug: 'action.submit',           translations: { en: 'Submit',                                              fr: 'Soumettre' } },
  { slug: 'action.continue',         translations: { en: 'Continue',                                            fr: 'Continuer' } },
  { slug: 'action.back',             translations: { en: 'Back',                                                fr: 'Retour' } },
  { slug: 'action.close',            translations: { en: 'Close',                                               fr: 'Fermer' } },
  { slug: 'action.add',              translations: { en: 'Add',                                                 fr: 'Ajouter' } },
  { slug: 'action.remove',           translations: { en: 'Remove',                                              fr: 'Supprimer' } },
  { slug: 'action.view',             translations: { en: 'View',                                                fr: 'Voir' } },
  { slug: 'action.loading',          translations: { en: 'Loading…',                                       fr: 'Chargement…' } },
  { slug: 'action.view_all',         translations: { en: 'View all',                                            fr: 'Tout voir' } },
  { slug: 'feedback.success',        translations: { en: 'Success',                                             fr: 'Succès' } },
  { slug: 'feedback.error',          translations: { en: 'Something went wrong',                                fr: 'Une erreur est survenue' } },
  { slug: 'feedback.not_found',      translations: { en: 'Page not found',                                      fr: 'Page introuvable' } },
  { slug: 'feedback.unauthorized',   translations: { en: 'You are not authorized to view this page',            fr: "Vous n'êtes pas autorisé à voir cette page" } },
  { slug: 'feedback.empty',          translations: { en: 'Nothing here yet',                                    fr: "Rien ici pour l'instant" } },
  { slug: 'feedback.required',       translations: { en: 'This field is required',                              fr: 'Ce champ est obligatoire' } },
  { slug: 'feedback.saving',         translations: { en: 'Saving…',                                        fr: 'Enregistrement…' } },
  { slug: 'feedback.saved',          translations: { en: 'Saved',                                               fr: 'Enregistré' } },
  { slug: 'feedback.confirm_delete', translations: { en: 'Are you sure you want to delete this?',               fr: 'Êtes-vous sûr de vouloir supprimer ceci ?' } },
  { slug: 'locale.select',           translations: { en: 'Select language',                                     fr: 'Choisir la langue' } },
  { slug: 'locale.current',          translations: { en: 'Current language',                                    fr: 'Langue actuelle' } },
  { slug: 'pagination.next',         translations: { en: 'Next',                                                fr: 'Suivant' } },
  { slug: 'pagination.previous',     translations: { en: 'Previous',                                            fr: 'Précédent' } },
  { slug: 'pagination.page',         translations: { en: 'Page',                                                fr: 'Page' } },
  { slug: 'pagination.of',           translations: { en: 'of',                                                  fr: 'sur' } },
  { slug: 'nav.pagination',          translations: { en: 'Pagination',                                          fr: 'Pagination' } },
  { slug: 'user.profile',            translations: { en: 'Profile',                                             fr: 'Profil' } },
  { slug: 'user.settings',           translations: { en: 'Settings',                                            fr: 'Paramètres' } },
  { slug: 'user.sign_in',            translations: { en: 'Sign in',                                             fr: 'Se connecter' } },
  { slug: 'user.sign_out',           translations: { en: 'Sign out',                                            fr: 'Se déconnecter' } },
  { slug: 'user.sign_up',            translations: { en: 'Sign up',                                             fr: "S'inscrire" } },
  { slug: 'user.email',              translations: { en: 'Email',                                               fr: 'Courriel' } },
  { slug: 'user.password',           translations: { en: 'Password',                                            fr: 'Mot de passe' } },
  { slug: 'user.forgot_password',    translations: { en: 'Forgot password?',                                    fr: 'Mot de passe oublié ?' } },
  { slug: 'user.sign_in.subtitle',   translations: { en: 'Enter your credentials to access the admin area.',    fr: 'Entrez vos identifiants pour accéder à la zone admin.' } },
  { slug: 'user.sign_in_with_google',translations: { en: 'Sign in with Google',                                 fr: 'Se connecter avec Google' } },
  { slug: 'table.id',                translations: { en: 'ID',                                                  fr: 'ID' } },
  { slug: 'table.name',              translations: { en: 'Name',                                                fr: 'Nom' } },
  { slug: 'table.status',            translations: { en: 'Status',                                              fr: 'Statut' } },
  { slug: 'table.date',              translations: { en: 'Date',                                                fr: 'Date' } },
  { slug: 'table.actions',           translations: { en: 'Actions',                                             fr: 'Actions' } },
  { slug: 'admin.title',                          translations: { en: 'Admin',                  fr: 'Admin' } },
  { slug: 'admin.nav.dashboard',                  translations: { en: 'Dashboard',              fr: 'Tableau de bord' } },
  { slug: 'admin.dashboard.title',                translations: { en: 'Dashboard',              fr: 'Tableau de bord' } },
  { slug: 'admin.dashboard.recent.title',         translations: { en: 'Recent records',         fr: 'Derniers enregistrements' } },
  { slug: 'admin.stats.key_metrics',              translations: { en: 'Key metrics',            fr: 'Indicateurs clés' } },
  { slug: 'admin.dashboard.stat.total_users',     translations: { en: 'Total users',            fr: 'Utilisateurs totaux' } },
  { slug: 'admin.dashboard.stat.active_sessions', translations: { en: 'Active sessions',        fr: 'Sessions actives' } },
  { slug: 'admin.dashboard.stat.published',       translations: { en: 'Published',              fr: 'Publié' } },
  { slug: 'admin.dashboard.stat.pending_review',  translations: { en: 'Pending review',         fr: 'En attente de révision' } },
  { slug: 'admin.nav.label',                      translations: { en: 'Admin navigation',       fr: 'Navigation admin' } },
  { slug: 'admin.nav.local_text',                 translations: { en: 'Content',                fr: 'Contenus' } },
  { slug: 'admin.local_text.title',               translations: { en: 'Content administration', fr: 'Administration des contenus' } },
  { slug: 'admin.local_text.slug',                translations: { en: 'Slug',                   fr: 'Identifiant' } },
  { slug: 'admin.local_text.scope',               translations: { en: 'Scope',                  fr: 'Portée' } },
  { slug: 'admin.local_text.new',                 translations: { en: 'New entry',              fr: 'Nouvelle entrée' } },
  { slug: 'admin.local_text.edit',                translations: { en: 'Edit entry',             fr: "Modifier l'entrée" } },
  { slug: 'admin.local_text.content',             translations: { en: 'Content',                fr: 'Contenu' } },
  { slug: 'admin.nav.locale',                     translations: { en: 'Locales',                fr: 'Locales' } },
  { slug: 'admin.locale.title',                   translations: { en: 'Locale administration',  fr: 'Administration des locales' } },
  { slug: 'admin.locale.code',                    translations: { en: 'Code',                   fr: 'Code' } },
  { slug: 'admin.locale.name',                    translations: { en: 'Name',                   fr: 'Nom' } },
  { slug: 'admin.locale.native_name',             translations: { en: 'Native name',            fr: 'Nom natif' } },
  { slug: 'admin.locale.dir',                     translations: { en: 'Text direction',          fr: 'Direction du texte' } },
  { slug: 'admin.locale.dir.ltr',                 translations: { en: 'Left to right',           fr: 'De gauche à droite' } },
  { slug: 'admin.locale.dir.rtl',                 translations: { en: 'Right to left',           fr: 'De droite à gauche' } },
  { slug: 'admin.locale.new',                     translations: { en: 'New locale',              fr: 'Nouvelle locale' } },
  { slug: 'admin.locale.edit',                    translations: { en: 'Edit locale',             fr: 'Modifier la locale' } },
  { slug: 'admin.nav.navigation_item',            translations: { en: 'Navigation',              fr: 'Navigation' } },
  { slug: 'admin.navigation_item.title',          translations: { en: 'Navigation administration', fr: 'Administration de la navigation' } },
  { slug: 'admin.navigation_item.href',           translations: { en: 'URL',                     fr: 'URL' } },
  { slug: 'admin.navigation_item.scope',          translations: { en: 'Scope',                   fr: 'Portée' } },
  { slug: 'admin.navigation_item.sort_order',     translations: { en: 'Sort order',              fr: 'Ordre de tri' } },
  { slug: 'admin.navigation_item.new',            translations: { en: 'New item',                fr: 'Nouvel élément' } },
  { slug: 'admin.navigation_item.edit',           translations: { en: 'Edit item',               fr: "Modifier l'élément" } },
  { slug: 'admin.navigation_item.active',         translations: { en: 'Active',                  fr: 'Actif' } },
  { slug: 'post.categories',                      translations: { en: 'Categories',              fr: 'Catégories' } },
  { slug: 'post.tags',                            translations: { en: 'Tags',                    fr: 'Étiquettes' } },
  { slug: 'post.comments',                        translations: { en: 'Comments',                fr: 'Commentaires' } },
];
