
  create table "public"."local_text" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "link" bigint not null,
    "locale" bigint not null,
    "content" text not null
      );


alter table "public"."local_text" enable row level security;


  create table "public"."local_text_link" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "slug" text not null,
    "scope" text,
    "entity_id" bigint
      );


alter table "public"."local_text_link" enable row level security;


  create table "public"."locale" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "code" text not null,
    "name" text not null,
    "native_name" text not null,
    "dir" text not null default 'ltr'::text
      );


alter table "public"."locale" enable row level security;

CREATE UNIQUE INDEX local_text_link_pkey ON public.local_text_link USING btree (id);

CREATE UNIQUE INDEX local_text_pkey ON public.local_text USING btree (id);

CREATE UNIQUE INDEX locale_pkey ON public.locale USING btree (id);

CREATE UNIQUE INDEX uq_local_text_entry ON public.local_text USING btree (link, locale);

CREATE UNIQUE INDEX uq_local_text_link_global ON public.local_text_link USING btree (slug, scope) NULLS NOT DISTINCT;

CREATE UNIQUE INDEX uq_local_text_link_scoped ON public.local_text_link USING btree (slug, scope, entity_id);

CREATE UNIQUE INDEX uq_locale_code ON public.locale USING btree (code);

alter table "public"."local_text" add constraint "local_text_pkey" PRIMARY KEY using index "local_text_pkey";

alter table "public"."local_text_link" add constraint "local_text_link_pkey" PRIMARY KEY using index "local_text_link_pkey";

alter table "public"."locale" add constraint "locale_pkey" PRIMARY KEY using index "locale_pkey";

alter table "public"."local_text" add constraint "local_text_link_fkey" FOREIGN KEY (link) REFERENCES public.local_text_link(id) ON DELETE RESTRICT not valid;

alter table "public"."local_text" validate constraint "local_text_link_fkey";

alter table "public"."local_text" add constraint "local_text_locale_fkey" FOREIGN KEY (locale) REFERENCES public.locale(id) ON DELETE RESTRICT not valid;

alter table "public"."local_text" validate constraint "local_text_locale_fkey";

alter table "public"."local_text" add constraint "uq_local_text_entry" UNIQUE using index "uq_local_text_entry";

alter table "public"."local_text_link" add constraint "uq_local_text_link_global" UNIQUE using index "uq_local_text_link_global" DEFERRABLE INITIALLY DEFERRED;

alter table "public"."local_text_link" add constraint "uq_local_text_link_scoped" UNIQUE using index "uq_local_text_link_scoped";

alter table "public"."locale" add constraint "uq_locale_code" UNIQUE using index "uq_locale_code";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_dictionary(user_locale_code text, fallback_locale_code text, scope_filter text DEFAULT NULL::text, entity_id_filter bigint DEFAULT NULL::bigint)
 RETURNS TABLE(link_id bigint, slug text, scope text, entity_id bigint, content text, locale_code text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  select distinct on (ltl.slug, ltl.scope, ltl.entity_id)
    ltl.id        as link_id,
    ltl.slug,
    ltl.scope,
    ltl.entity_id,
    lt.content,
    l.code        as locale_code
  from public.local_text lt
  join public.local_text_link ltl on ltl.id = lt.link
  join public.locale l on l.id = lt.locale
  where l.code in (user_locale_code, fallback_locale_code)
    and (
      scope_filter is null and ltl.scope is null
      or ltl.scope = scope_filter
    )
    and (
      entity_id_filter is null and ltl.entity_id is null
      or ltl.entity_id = entity_id_filter
    )
  order by
    ltl.slug,
    ltl.scope,
    ltl.entity_id,
    case when l.code = user_locale_code then 0 else 1 end
$function$
;

grant delete on table "public"."local_text" to "anon";

grant insert on table "public"."local_text" to "anon";

grant references on table "public"."local_text" to "anon";

grant select on table "public"."local_text" to "anon";

grant trigger on table "public"."local_text" to "anon";

grant truncate on table "public"."local_text" to "anon";

grant update on table "public"."local_text" to "anon";

grant delete on table "public"."local_text" to "authenticated";

grant insert on table "public"."local_text" to "authenticated";

grant references on table "public"."local_text" to "authenticated";

grant select on table "public"."local_text" to "authenticated";

grant trigger on table "public"."local_text" to "authenticated";

grant truncate on table "public"."local_text" to "authenticated";

grant update on table "public"."local_text" to "authenticated";

grant delete on table "public"."local_text" to "service_role";

grant insert on table "public"."local_text" to "service_role";

grant references on table "public"."local_text" to "service_role";

grant select on table "public"."local_text" to "service_role";

grant trigger on table "public"."local_text" to "service_role";

grant truncate on table "public"."local_text" to "service_role";

grant update on table "public"."local_text" to "service_role";

grant delete on table "public"."local_text_link" to "anon";

grant insert on table "public"."local_text_link" to "anon";

grant references on table "public"."local_text_link" to "anon";

grant select on table "public"."local_text_link" to "anon";

grant trigger on table "public"."local_text_link" to "anon";

grant truncate on table "public"."local_text_link" to "anon";

grant update on table "public"."local_text_link" to "anon";

grant delete on table "public"."local_text_link" to "authenticated";

grant insert on table "public"."local_text_link" to "authenticated";

grant references on table "public"."local_text_link" to "authenticated";

grant select on table "public"."local_text_link" to "authenticated";

grant trigger on table "public"."local_text_link" to "authenticated";

grant truncate on table "public"."local_text_link" to "authenticated";

grant update on table "public"."local_text_link" to "authenticated";

grant delete on table "public"."local_text_link" to "service_role";

grant insert on table "public"."local_text_link" to "service_role";

grant references on table "public"."local_text_link" to "service_role";

grant select on table "public"."local_text_link" to "service_role";

grant trigger on table "public"."local_text_link" to "service_role";

grant truncate on table "public"."local_text_link" to "service_role";

grant update on table "public"."local_text_link" to "service_role";

grant delete on table "public"."locale" to "anon";

grant insert on table "public"."locale" to "anon";

grant references on table "public"."locale" to "anon";

grant select on table "public"."locale" to "anon";

grant trigger on table "public"."locale" to "anon";

grant truncate on table "public"."locale" to "anon";

grant update on table "public"."locale" to "anon";

grant delete on table "public"."locale" to "authenticated";

grant insert on table "public"."locale" to "authenticated";

grant references on table "public"."locale" to "authenticated";

grant select on table "public"."locale" to "authenticated";

grant trigger on table "public"."locale" to "authenticated";

grant truncate on table "public"."locale" to "authenticated";

grant update on table "public"."locale" to "authenticated";

grant delete on table "public"."locale" to "service_role";

grant insert on table "public"."locale" to "service_role";

grant references on table "public"."locale" to "service_role";

grant select on table "public"."locale" to "service_role";

grant trigger on table "public"."locale" to "service_role";

grant truncate on table "public"."locale" to "service_role";

grant update on table "public"."locale" to "service_role";


  create policy "local_text_admin_write"
  on "public"."local_text"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'role'::text) = 'admin'::text))
with check (((auth.jwt() ->> 'role'::text) = 'admin'::text));



  create policy "local_text_public_read"
  on "public"."local_text"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "local_text_link_admin_write"
  on "public"."local_text_link"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'role'::text) = 'admin'::text))
with check (((auth.jwt() ->> 'role'::text) = 'admin'::text));



  create policy "local_text_link_public_read"
  on "public"."local_text_link"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "locale_admin_write"
  on "public"."locale"
  as permissive
  for all
  to authenticated
using (((auth.jwt() ->> 'role'::text) = 'admin'::text))
with check (((auth.jwt() ->> 'role'::text) = 'admin'::text));



  create policy "locale_public_read"
  on "public"."locale"
  as permissive
  for select
  to anon, authenticated
using (true);



