create table public.locale (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  code        text not null,
  name        text not null,
  native_name text not null,
  dir         text not null default 'ltr',
  constraint uq_locale_code unique (code)
);

alter table public.locale enable row level security;

create policy "locale_public_read"
  on public.locale for select
  to anon, authenticated
  using (true);

create policy "locale_admin_write"
  on public.locale for all
  to authenticated
  using (auth.jwt() ->> 'role' = 'admin')
  with check (auth.jwt() ->> 'role' = 'admin');
