create table public.local_text_link (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  slug        text not null,
  scope       text null,
  entity_id   bigint null,
  constraint uq_local_text_link_scoped unique (slug, scope, entity_id),
  constraint uq_local_text_link_global unique nulls not distinct (slug, scope)
    deferrable initially deferred
);

alter table public.local_text_link enable row level security;

create policy "local_text_link_public_read"
  on public.local_text_link for select
  to anon, authenticated
  using (true);

create policy "local_text_link_admin_write"
  on public.local_text_link for all
  to authenticated
  using (auth.jwt() ->> 'role' = 'admin')
  with check (auth.jwt() ->> 'role' = 'admin');
