create table public.local_text (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  link        bigint not null references public.local_text_link (id) on delete restrict,
  locale      bigint not null references public.locale (id) on delete restrict,
  content     text not null,
  constraint uq_local_text_entry unique (link, locale)
);

alter table public.local_text enable row level security;

create policy "local_text_public_read"
  on public.local_text for select
  to anon, authenticated
  using (true);

create policy "local_text_admin_write"
  on public.local_text for all
  to authenticated
  using (auth.jwt() ->> 'role' = 'admin')
  with check (auth.jwt() ->> 'role' = 'admin');
