create table public.navigation_item (
  id                  bigint generated by default as identity primary key,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  local_text_link_id  bigint not null references public.local_text_link (id),
  href                text not null,
  scope               text not null,
  sort_order          integer not null default 0,
  active              boolean not null default true,
  constraint uq_navigation_item_href_scope unique (href, scope)
);

create index idx_navigation_item_scope_order
  on public.navigation_item (scope, sort_order)
  where active;

alter table public.navigation_item enable row level security;

-- All roles can read active navigation items; items are filtered by active in the query.
create policy "navigation_item_public_read"
  on public.navigation_item for select
  to anon, authenticated
  using (active);

create policy "navigation_item_admin_write"
  on public.navigation_item for all
  to authenticated
  using (auth.jwt() ->> 'role' = 'admin')
  with check (auth.jwt() ->> 'role' = 'admin');
